services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: tania
      POSTGRES_PASSWORD: taniasbank_pw
      POSTGRES_DB: taniasbank
    ports:
      - "5432:5432"
    volumes:
      - taniasbank_pg:/var/lib/postgresql/data

volumes:
  taniasbank_pg: